# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    LaxCorp\ProfileAdminBundle\Controller\TariffController:
    LaxCorp\ProfileAdminBundle\Controller\ProfileController:
        arguments:
            $blocks: '%sonata.admin.configuration.dashboard_blocks%'
    LaxCorp\ProfileAdminBundle\Form\CreateProfileType:
        arguments:
            $catalogHostingEnabled: '%catalog_hosting_enabled%'
            $customerExpirationDateTo: '%customer_expiration_date_to%'
    LaxCorp\ProfileAdminBundle\Form\EditProfileType:
        arguments:
            $catalogHostingEnabled: '%catalog_hosting_enabled%'
